### ISSUE TITLE
[Bug] - When "Inserting column left/right" other column data is removed

### ISSUE THREAD

**Issue by Inferno118899** [DillonHammill/DataEditR#12]
1) Column data _to the right_ is removed when I add more than one Column. It seems to only happen after I've already added one Column to the left or right. Pictured below with mtcars dataset
```
mtcars_new <- DataEditR::data_edit(mtcars,
                        save_as = "mtcars.csv",
                        write_fun = "write.table",
                        write_args = list(sep = ",",
                                          row.names = TRUE))
```

![2020-12-10 23-46-53](https://user-images.githubusercontent.com/25239347/101774345-161fdf80-3b42-11eb-8d60-86775e5baeed.png)
![2020-12-10 23-38-39](https://user-images.githubusercontent.com/25239347/101773641-2e432f00-3b41-11eb-98df-b6f725e167e9.png)

2) If I rename a column after entering in data, that variables' data is removed and I have to re-enter the data all over again.

![2020-12-10 23-31-51](https://user-images.githubusercontent.com/25239347/101772756-e7086e80-3b3f-11eb-8c5a-02678d91a259.png)

Fantastic work on the package too and such great progress. Very excited by it. Keep up the great work.

**Comment by DillonHammill** [comment]
Thanks for reporting this @Inferno118899, I just pushed a fix to patch this. It is actually a `rhandsontable` bug that is difficult to track down and fix. So instead I have just patched the code in `dataEdit` to ensure that all the original data is retained when columns are added.

**Comment by DillonHammill** [comment]
Good news! I managed to track down the problem in `rhandsontable`! Turns out new columns get assigned a column class of `logical` as they are initiated with NA values and when the data is entered it is coerced to class `logical` as well. This forces charcters/numerics to be converted into NAs and so it essentially deletes these entries from the table. I have pushed the relevant fix to my fork of `rhandsontable` to ensure that columns starting with class logical are converted to a more appropriate class when data is entered. This means that no changes were required to `DataEditR but you will need to update your `rhandsontable` as below:
```{r}
devtools::install_github("DillonHammill/rhandsontable")
```

Please let me know how you go, and feel free to reopen this issue if it remains unresolved.

**Comment by Inferno118899** [comment]
Well Done @DillonHammill !! Great work 👍
